
name: CI

on:
  push:
    branches: [main]
    tags:
      - v*
  pull_request:

jobs:
  say_hi_from_ci:
    runs-on: ubuntu-latest
    steps:
      - run: echo "hi from ci"
      - run: echo ${{ github.ref }}
      - run: echo ${{ github.event.ref }}
