name: Upload Benchmarks

on:
  push:
    branches:
      - main
    tags: 
      - v*

jobs:
  upload_benchmarks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 14 x64
        uses: actions/setup-node@v2
        with:
          node-version: 14
          architecture: x64

      #- name: Install
      #  run: npm ci

      #- name: Build benchmarks
      #  run: npm run build-benchmarks

      - name: Upload to GitHub Pages (main)
        if: startsWith(github.ref, 'refs/heads/main')
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: bench/versions
          destination_dir: benchmarks/main
      
      - name: Upload to GitHub Pages (tag)
        if: startsWith(github.ref, 'refs/tags/v')
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: bench/versions
          destination_dir: benchmarks/${GITHUB_REF##*/}
