name: Release

on:
  push:
    branches:
      - main
    tags: 
      - v*

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: main
        if: contains(${{ github.ref }}, 'ref/heads/main')
        run: echo "trigger was push to main"
      
      - name: tag
        if: contains(${{ github.ref }}, 'ref/tags')
        run: echo "trigger was new tag"
