name: Release

on:
  workflow_dispatch

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: main

      - name: Get version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.1.0
      
      - run: echo ${{ steps.package-version.outputs.current-version }}

      - name: Check tag does not exist yet
        run: if git rev-list v${{ steps.package-version.outputs.current-version }}; then exit 1; fi

      - name: Tag commit and push
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ steps.package-version.outputs.current-version }}
