name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags: 
      - v*

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: print ref
        run: echo ${{ github.ref }}
