name: Release

on:
  push:
    branches:
      - main
    tags: 
      - v*

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: main
        if: startsWith(github.ref, 'refs/heads/main')
        run: echo "trigger was push to main"
      
      - name: tag
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          echo "trigger was new tag"
          echo ${GITHUB_REF##*/}
